sequence='CTGCTTCTGTTGACTCATGTTTGCGTGTGTCTCCCCTACTAACTTTTTGCAGCCAACACTGGTTGAATCAACTGGAGAGCCGAAATACAATGAGATCTGACCGGCGGCGTGGCTCACCGAATGAATTAAGCTGATTAGTAGCTTATTGTAATCGGTGCCGGAACTCTTGGGTTTAAGAAGTTAAAGGGGTCTTATCCGGTCGGGGGATCTCTTTACATTTATACCAGTGGGGCAGGGCGGGAATGCTCCGACGAGCCGCCTAGAAGGAAGTGACGGTGATTCCCTCATACGCCGTACCAAGCGCCTACGAGTGCCCAAGGAGAAGCCGAAAACCTAGTCAAACTTACTCTCGCGTCTCCGCACGTAAACAGAGATAACCTTATAGATTCGTACTGACAGCGAACCAGGTTACTGCACATCCGGGCGACATATCCTTGACTGGTCGTGCATGTATGCTTTCGCCGGACGACCCAGTACACGTGGGTACTGGGCAAACACGTGGGGTGAGCCGAACCGGATACTGAGGCCTAAGCCCGTTCGGACCTAGCGTTTCTCTGCCTAGCTCTGCGCCGTTTAGGCTAACCATCGTGGCTGTAATCTCTGTGGATTGGATCTAGCCGCGACTACGTCGCTACTTTAGAATGTAGTCAAACGCGCGGATATGTAGGATCTTAAAAAGTGTATCAAACCGGCAGTAACGCGGGAGTAGATTTCGCGATACGTACCACGAGCTCTTCGCAGTATCCAGATTGGGACGGCTATATTTATTCGAGGATGGAGTAGTAAAAAATCTTCTACACGACTTTCGGGATTCAGGGGAGGCCACTTAGCTTCATCCGGGAAGTTGGGCCTGTTCGTCAATTGCCCGTACAGCTCAGGCTGCTCGTATGAATGTCTAATGCTTATTCGGGGCCCAACTTTTCTACGCGACCTCAAAGCGAAGGACTAAACATGCGGGCACGGAGCCGGGGGGCGAACTAAGTACGTGTTGGCCCAA'
a = 0
g = 0
c = 0
t = 0
for symbol in sequence:
    if symbol == 'A':
        a = a+1
    elif symbol == 'G':
        g = g+1
    elif symbol == 'C':
        c = c+1
    else:
        t = t+1    
print ( a,c,g,t)